### ISSUE TITLE
Rollup throws if there are no style (scss) tags

### ISSUE THREAD

**Issue by cocoastorm** [znck/vue-plugin#11]
`[!] No input specified: provide a file name or a source string to process`

I believe this issue is caused because in `config/rollup-plugin-vue.config.js` it's trying to use `node-sass` to render/compile scss to css. But there are no scss styles to compile and it throws `err`.

This causes the rollup build to fail.

**Comment by znck** [comment]
This config file is outdated. Use this (https://vuejs.github.io/rollup-plugin-vue/#/en/2.3).
