### ISSUE TITLE
how should I test my components?

### ISSUE THREAD

**Issue by sobolevn** [znck/vue-plugin#4]
Hello, I am currently thinking about migrating my components to the `rollup`. I have found your plugin, and this demo project. So, my question is: how should I integrate tests into this workflow?

You can have a look at my current build and test setup: https://github.com/wemake-services/vue-material-input

I am currently using this stack:
- `vue2` with single-file components
- `webpack` (version 1) for building
- `karma` with `phantomjs` as browser and `mocha` as a test framework

Any ideas or suggestions? Thanks!

**Comment by znck** [comment]
I hope #5 would help you to implement unit tests. I am caught up with stuff and I won't be able to finish #5 until early next year. 

If you got any queries, post on #5.
