### ISSUE TITLE
can we add it to vuejs official templates?

### ISSUE THREAD

**Issue by aladdin-add** [znck/vue-plugin#8]

**Comment by znck** [comment]
Right now all templates are for applications.

IMO plugins are small and they need not to be constrained to a bias. Though, I'll discuss with the team if we should include plugin templates too.

https://github.com/posva/vue-plugin-template is a full featured template, I'd recommend that.

**Comment by aladdin-add** [comment]
thanks for your response(and the recommend). it is very useful, but as far as I can see, many people may not be aware of it. or maybe we can add a linking to it in the vuejs docs?

**Comment by znck** [comment]
We'll definitely add to Vue Curated (successor/better-version of awesome-vue).
